// sigil: REPAIR
//
// Policy-gate remediation helpers: owner routing, task title/notes templates,
// and deterministic task IDs derived from (source, blocker, timestamp).

use chrono::Utc;
use sha2::{Digest, Sha256};

pub(super) fn remediation_owner(blocker: &str) -> &'static str {
    match blocker {
        "triad_threshold" => "prometheus",
        "confidence_threshold" => "athena",
        "opposition_coverage" => "athena",
        "citation_integrity" => "athena",
        "hash_chain_invalid" => "warden",
        _ => "prometheus",
    }
}

pub(super) fn remediation_title(source_id: &str, blocker: &str) -> String {
    match blocker {
        "triad_threshold" => format!("Raise triad readiness for {source_id}"),
        "confidence_threshold" => format!("Improve confidence evidence for {source_id}"),
        "opposition_coverage" => format!("Add opposing viewpoints for {source_id}"),
        "citation_integrity" => format!("Repair citation integrity for {source_id}"),
        "hash_chain_invalid" => format!("Repair hash chain integrity for {source_id}"),
        _ => format!("Resolve policy gate blocker {blocker} for {source_id}"),
    }
}

pub(super) fn remediation_notes(source_id: &str, blocker: &str) -> String {
    format!(
        "Generated by ATHENA policy gate. Source {source_id} blocked by {blocker}. \
         Add missing evidence and rerun deep analysis."
    )
}

pub(super) fn remediation_task_id(source_id: &str, blocker: &str) -> String {
    let input = format!(
        "{source_id}:{blocker}:{}",
        Utc::now().timestamp_nanos_opt().unwrap_or_default()
    );
    let mut hasher = Sha256::new();
    hasher.update(input.as_bytes());
    let hex = hasher
        .finalize()
        .iter()
        .map(|b| format!("{b:02x}"))
        .collect::<String>();
    format!("tsk_policy_{}", &hex[..12])
}
