use crate::adaptive::service::types::{ModelState, ProviderState};

pub fn env_key_present(key: &str) -> bool {
    std::env::var(key)
        .map(|value| !value.trim().is_empty())
        .unwrap_or(false)
}

pub fn default_providers() -> Vec<ProviderState> {
    vec![
        ProviderState {
            id: "mistral".to_string(),
            name: "Mistral API".to_string(),
            base_url: Some("https://api.mistral.ai/v1".to_string()),
            api_key_env: Some("MISTRAL_API_KEY".to_string()),
            access_tier: "mixed".to_string(),
            quality_band: "high".to_string(),
            intelligence_refreshed_at_utc: None,
            probe_model: None,
            probe_profile: None,
            enabled: true,
            has_api_key: env_key_present("MISTRAL_API_KEY"),
            healthy: true,
            in_cooldown: false,
            cooldown_until_utc: None,
            cooldown_backoff_seconds: 120,
            requests_per_minute: Some(60),
            requests_used_minute: 0,
            minute_window_started_utc: None,
            requests_per_day: Some(1_000),
            requests_used_day: 0,
            day_window_started_utc: None,
            error_count: 0,
            consecutive_failures: 0,
            consecutive_successes: 0,
            last_error: None,
            avg_latency_ms: None,
            active_connections: 0,
            last_reservation_utc: None,
            supports_tools: true,
            supports_structured_output: true,
            driver: "openai_compat".to_string(),
            hermes_bin: None,
            hermes_provider: None,
            hermes_toolsets: None,
            models: vec![ModelState {
                aliases: vec![],
                id: "mistral-small-2603".to_string(),
                capable_tasks: vec![
                    "code".to_string(),
                    "research".to_string(),
                    "reasoning".to_string(),
                    "chat".to_string(),
                    "summary".to_string(),
                    "background".to_string(),
                ],
                context_window: 256_000,
                is_default: true,
                healthy: true,
                in_cooldown: false,
                cooldown_until_utc: None,
                consecutive_failures: 0,
                consecutive_successes: 0,
                last_error: None,
                avg_latency_ms: None,
                cost_per_million_tokens_in: None,
                cost_per_million_tokens_out: None,
                capabilities: crate::adaptive::service::types::ModelCapabilities::default(),
                streaming_validated: None,
            }],
        },
        ProviderState {
            id: "zai".to_string(),
            name: "Z.AI / GLM".to_string(),
            base_url: Some("https://api.z.ai/api/paas/v4".to_string()),
            api_key_env: Some("ZAI_API_KEY".to_string()),
            access_tier: "paid_cloud".to_string(),
            quality_band: "high".to_string(),
            intelligence_refreshed_at_utc: None,
            probe_model: None,
            probe_profile: None,
            enabled: true,
            has_api_key: env_key_present("ZAI_API_KEY"),
            healthy: true,
            in_cooldown: false,
            cooldown_until_utc: None,
            cooldown_backoff_seconds: 120,
            requests_per_minute: Some(60),
            requests_used_minute: 0,
            minute_window_started_utc: None,
            requests_per_day: Some(10_000),
            requests_used_day: 0,
            day_window_started_utc: None,
            error_count: 0,
            consecutive_failures: 0,
            consecutive_successes: 0,
            last_error: None,
            avg_latency_ms: None,
            active_connections: 0,
            last_reservation_utc: None,
            supports_tools: true,
            supports_structured_output: true,
            driver: "openai_compat".to_string(),
            hermes_bin: None,
            hermes_provider: None,
            hermes_toolsets: None,
            models: vec![ModelState {
                aliases: vec![],
                id: "glm-5".to_string(),
                capable_tasks: vec![
                    "code".to_string(),
                    "research".to_string(),
                    "reasoning".to_string(),
                    "chat".to_string(),
                    "summary".to_string(),
                    "background".to_string(),
                ],
                context_window: 200_000,
                is_default: true,
                healthy: true,
                in_cooldown: false,
                cooldown_until_utc: None,
                consecutive_failures: 0,
                consecutive_successes: 0,
                last_error: None,
                avg_latency_ms: None,
                cost_per_million_tokens_in: None,
                cost_per_million_tokens_out: None,
                capabilities: crate::adaptive::service::types::ModelCapabilities::default(),
                streaming_validated: None,
            }],
        },
        ProviderState {
            id: "anthropic".to_string(),
            name: "Anthropic Claude".to_string(),
            base_url: Some("https://api.anthropic.com/v1".to_string()),
            api_key_env: Some("ANTHROPIC_API_KEY".to_string()),
            access_tier: "paid_cloud".to_string(),
            quality_band: "high".to_string(),
            intelligence_refreshed_at_utc: None,
            probe_model: None,
            probe_profile: None,
            enabled: true,
            has_api_key: env_key_present("ANTHROPIC_API_KEY"),
            healthy: true,
            in_cooldown: false,
            cooldown_until_utc: None,
            cooldown_backoff_seconds: 120,
            requests_per_minute: Some(50),
            requests_used_minute: 0,
            minute_window_started_utc: None,
            requests_per_day: Some(5000),
            requests_used_day: 0,
            day_window_started_utc: None,
            error_count: 0,
            consecutive_failures: 0,
            consecutive_successes: 0,
            last_error: None,
            avg_latency_ms: None,
            active_connections: 0,
            last_reservation_utc: None,
            supports_tools: true,
            supports_structured_output: true,
            driver: "openai_compat".to_string(),
            hermes_bin: None,
            hermes_provider: None,
            hermes_toolsets: None,
            models: vec![ModelState {
                aliases: vec![],
                id: "claude-3-5-sonnet-20241022".to_string(),
                capable_tasks: vec![
                    "code".to_string(),
                    "research".to_string(),
                    "reasoning".to_string(),
                    "chat".to_string(),
                    "summary".to_string(),
                ],
                context_window: 200_000,
                is_default: true,
                healthy: true,
                in_cooldown: false,
                cooldown_until_utc: None,
                consecutive_failures: 0,
                consecutive_successes: 0,
                last_error: None,
                avg_latency_ms: None,
                cost_per_million_tokens_in: None,
                cost_per_million_tokens_out: None,
                capabilities: crate::adaptive::service::types::ModelCapabilities::default(),
                streaming_validated: None,
            }],
        },
        ProviderState {
            id: "nvidia".to_string(),
            name: "NVIDIA API Catalog".to_string(),
            base_url: Some("https://integrate.api.nvidia.com/v1".to_string()),
            api_key_env: Some("NVIDIA_API_KEY".to_string()),
            access_tier: "mixed".to_string(),
            quality_band: "high".to_string(),
            intelligence_refreshed_at_utc: None,
            probe_model: None,
            probe_profile: None,
            enabled: true,
            has_api_key: env_key_present("NVIDIA_API_KEY"),
            healthy: true,
            in_cooldown: false,
            cooldown_until_utc: None,
            cooldown_backoff_seconds: 120,
            requests_per_minute: Some(60),
            requests_used_minute: 0,
            minute_window_started_utc: None,
            requests_per_day: Some(1_000),
            requests_used_day: 0,
            day_window_started_utc: None,
            error_count: 0,
            consecutive_failures: 0,
            consecutive_successes: 0,
            last_error: None,
            avg_latency_ms: None,
            active_connections: 0,
            last_reservation_utc: None,
            supports_tools: true,
            supports_structured_output: true,
            driver: "openai_compat".to_string(),
            hermes_bin: None,
            hermes_provider: None,
            hermes_toolsets: None,
            models: vec![ModelState {
                aliases: vec![],
                id: "qwen/qwen3-coder-480b-a35b-instruct".to_string(),
                capable_tasks: vec![
                    "code".to_string(),
                    "research".to_string(),
                    "reasoning".to_string(),
                    "chat".to_string(),
                    "summary".to_string(),
                    "background".to_string(),
                ],
                context_window: 128_000,
                is_default: true,
                healthy: true,
                in_cooldown: false,
                cooldown_until_utc: None,
                consecutive_failures: 0,
                consecutive_successes: 0,
                last_error: None,
                avg_latency_ms: None,
                cost_per_million_tokens_in: None,
                cost_per_million_tokens_out: None,
                capabilities: crate::adaptive::service::types::ModelCapabilities::default(),
                streaming_validated: None,
            }],
        },
        ProviderState {
            id: "cerebras".to_string(),
            name: "Cerebras Cloud".to_string(),
            base_url: Some("https://api.cerebras.ai/v1".to_string()),
            api_key_env: Some("CEREBRAS_API_KEY".to_string()),
            access_tier: "free_cloud".to_string(),
            quality_band: "high".to_string(),
            intelligence_refreshed_at_utc: None,
            probe_model: None,
            probe_profile: None,
            enabled: true,
            has_api_key: env_key_present("CEREBRAS_API_KEY"),
            healthy: true,
            in_cooldown: false,
            cooldown_until_utc: None,
            cooldown_backoff_seconds: 120,
            requests_per_minute: Some(30),
            requests_used_minute: 0,
            minute_window_started_utc: None,
            requests_per_day: Some(1_000_000),
            requests_used_day: 0,
            day_window_started_utc: None,
            error_count: 0,
            consecutive_failures: 0,
            consecutive_successes: 0,
            last_error: None,
            avg_latency_ms: None,
            active_connections: 0,
            last_reservation_utc: None,
            supports_tools: true,
            supports_structured_output: true,
            driver: "openai_compat".to_string(),
            hermes_bin: None,
            hermes_provider: None,
            hermes_toolsets: None,
            models: vec![ModelState {
                aliases: vec![],
                id: "llama3.1-8b".to_string(),
                capable_tasks: vec![
                    "code".to_string(),
                    "research".to_string(),
                    "reasoning".to_string(),
                    "chat".to_string(),
                ],
                context_window: 128_000,
                is_default: true,
                healthy: true,
                in_cooldown: false,
                cooldown_until_utc: None,
                consecutive_failures: 0,
                consecutive_successes: 0,
                last_error: None,
                avg_latency_ms: None,
                cost_per_million_tokens_in: None,
                cost_per_million_tokens_out: None,
                capabilities: crate::adaptive::service::types::ModelCapabilities::default(),
                streaming_validated: None,
            }],
        },
        ProviderState {
            id: "groq".to_string(),
            name: "Groq".to_string(),
            base_url: Some("https://api.groq.com/openai/v1".to_string()),
            api_key_env: Some("GROQ_API_KEY".to_string()),
            access_tier: "free_cloud".to_string(),
            quality_band: "high".to_string(),
            intelligence_refreshed_at_utc: None,
            probe_model: None,
            probe_profile: None,
            enabled: true,
            has_api_key: env_key_present("GROQ_API_KEY"),
            healthy: true,
            in_cooldown: false,
            cooldown_until_utc: None,
            cooldown_backoff_seconds: 120,
            requests_per_minute: Some(30),
            requests_used_minute: 0,
            minute_window_started_utc: None,
            requests_per_day: Some(14_400),
            requests_used_day: 0,
            day_window_started_utc: None,
            error_count: 0,
            consecutive_failures: 0,
            consecutive_successes: 0,
            last_error: None,
            avg_latency_ms: None,
            active_connections: 0,
            last_reservation_utc: None,
            supports_tools: true,
            supports_structured_output: true,
            driver: "openai_compat".to_string(),
            hermes_bin: None,
            hermes_provider: None,
            hermes_toolsets: None,
            models: vec![ModelState {
                aliases: vec![],
                id: "llama-3.3-70b-versatile".to_string(),
                capable_tasks: vec![
                    "code".to_string(),
                    "research".to_string(),
                    "reasoning".to_string(),
                    "chat".to_string(),
                    "summary".to_string(),
                ],
                context_window: 128_000,
                is_default: true,
                healthy: true,
                in_cooldown: false,
                cooldown_until_utc: None,
                consecutive_failures: 0,
                consecutive_successes: 0,
                last_error: None,
                avg_latency_ms: None,
                cost_per_million_tokens_in: None,
                cost_per_million_tokens_out: None,
                capabilities: crate::adaptive::service::types::ModelCapabilities::default(),
                streaming_validated: None,
            }],
        },
        ProviderState {
            id: "google".to_string(),
            name: "Google AI Studio".to_string(),
            base_url: Some("https://generativelanguage.googleapis.com/v1beta/openai".to_string()),
            api_key_env: Some("GEMINI_API_KEY".to_string()),
            access_tier: "free_cloud".to_string(),
            quality_band: "high".to_string(),
            intelligence_refreshed_at_utc: None,
            probe_model: None,
            probe_profile: None,
            enabled: true,
            has_api_key: env_key_present("GEMINI_API_KEY"),
            healthy: true,
            in_cooldown: false,
            cooldown_until_utc: None,
            cooldown_backoff_seconds: 120,
            requests_per_minute: Some(10),
            requests_used_minute: 0,
            minute_window_started_utc: None,
            requests_per_day: Some(1_000),
            requests_used_day: 0,
            day_window_started_utc: None,
            error_count: 0,
            consecutive_failures: 0,
            consecutive_successes: 0,
            last_error: None,
            avg_latency_ms: None,
            active_connections: 0,
            last_reservation_utc: None,
            supports_tools: true,
            supports_structured_output: true,
            driver: "openai_compat".to_string(),
            hermes_bin: None,
            hermes_provider: None,
            hermes_toolsets: None,
            models: vec![ModelState {
                aliases: vec![],
                id: "gemini-2.0-flash".to_string(),
                capable_tasks: vec![
                    "code".to_string(),
                    "research".to_string(),
                    "chat".to_string(),
                    "summary".to_string(),
                ],
                context_window: 1_000_000,
                is_default: true,
                healthy: true,
                in_cooldown: false,
                cooldown_until_utc: None,
                consecutive_failures: 0,
                consecutive_successes: 0,
                last_error: None,
                avg_latency_ms: None,
                cost_per_million_tokens_in: None,
                cost_per_million_tokens_out: None,
                capabilities: crate::adaptive::service::types::ModelCapabilities::default(),
                streaming_validated: None,
            }],
        },
        ProviderState {
            id: "local_fallback".to_string(),
            name: "Local Llama.cpp Fallback".to_string(),
            base_url: Some(format!("http://{}:{}/v1", "127.0.0.1", 9337)),
            api_key_env: None,
            access_tier: "local".to_string(),
            quality_band: "medium".to_string(),
            intelligence_refreshed_at_utc: None,
            probe_model: None,
            probe_profile: None,
            enabled: true,
            has_api_key: true,
            healthy: true,
            in_cooldown: false,
            cooldown_until_utc: None,
            cooldown_backoff_seconds: 120,
            requests_per_minute: None,
            requests_used_minute: 0,
            minute_window_started_utc: None,
            requests_per_day: None,
            requests_used_day: 0,
            day_window_started_utc: None,
            error_count: 0,
            consecutive_failures: 0,
            consecutive_successes: 0,
            last_error: None,
            avg_latency_ms: None,
            active_connections: 0,
            last_reservation_utc: None,
            supports_tools: true,
            supports_structured_output: true,
            driver: "openai_compat".to_string(),
            hermes_bin: None,
            hermes_provider: None,
            hermes_toolsets: None,
            models: vec![ModelState {
                aliases: vec![],
                id: std::env::var("ARDA_LOCAL_MODEL")
                    .unwrap_or_else(|_| "Qwen3-8B-Q4_K_M".to_string()),
                capable_tasks: vec![
                    "code".to_string(),
                    "research".to_string(),
                    "reasoning".to_string(),
                    "chat".to_string(),
                    "summary".to_string(),
                    "background".to_string(),
                ],
                context_window: 16_384,
                is_default: true,
                healthy: true,
                in_cooldown: false,
                cooldown_until_utc: None,
                consecutive_failures: 0,
                consecutive_successes: 0,
                last_error: None,
                avg_latency_ms: None,
                cost_per_million_tokens_in: None,
                cost_per_million_tokens_out: None,
                capabilities: crate::adaptive::service::types::ModelCapabilities::default(),
                streaming_validated: None,
            }],
        },
    ]
}
