[package]
name = "arda-launcher"
version = "0.1.0"
description = "A Tauri App"
authors = ["you"]
edition = "2021"

[lib]
name = "arda_launcher_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-opener = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
anyhow = "1"
chrono = { version = "0.4", features = ["serde"] }
toml = "0.8"
sysinfo = "0.30"
arda-core = { workspace = true }
arda-contract-registry = { workspace = true }

[profile.release]
codegen-units = 1
lto = true
opt-level = 3
panic = "abort"
strip = true
